author: "Tobe O <thosakwe@gmail.com>"
description: "source_gen based template engine for the Angel framework."
homepage: "https://github.com/angel-dart/template.git"
name: "angel_template"
version: "0.0.0"
dependencies: 
  build: "^0.6.3"
  charcode: "^1.0.0"
  code_builder: "^1.0.0-alpha+7"
  path: "^1.4.1"
  source_gen: "^0.5.2"
dev_dependencies:
  angel_framework: "^1.0.0-dev"
  test: "^0.12.15"
environment: 
  sdk: ">=1.19.0"
